# Generated by Django 5.0.4 on 2024-05-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pemain',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')])),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PenulisSkenario',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')])),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sutradara',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')])),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
        ),
    ]
