# Generated by Django 5.0.4 on 2024-05-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langganan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='device_support',
            new_name='dukungan_perangkat',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='screen_resolution',
            new_name='resolusi_layar',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='package',
            new_name='paket',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='pengguna',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='end_date',
            new_name='tanggal_berakhir',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='start_date',
            new_name='tanggal_dimulai',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_method',
            new_name='metode_pembayaran',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='package',
            new_name='paket',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='pengguna',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_timestamp',
            new_name='timestamp_pembayaran',
        ),
    ]
